Department of Physics, University of Pisa (AA 2022-2023)

### Multimessenger Physics Laboratory tutorial series



## Tutorial 01 - Basics of Numerical Python
#### (M. Razzano, Feb 21, 2023)

In this tutorial we will see how to use the basic functionalities of Numerical Python (numpy) to read and manipulate data

In [1]:
#first, import and check the version
import numpy as np
np.__version__

'1.22.0'

<h2>Basic definitions</h2>

In [3]:
#What is the difference between a list and a numpy array?
l = [1,3,4,5,1,24]

l_np = np.array([1,3,4,5,1,24])

# These are printed in the same way, but are different object!
# Try operation and manipulation methods for looking at these differences
print(l)
print(l_np)

[1, 3, 4, 5, 1, 24]
[ 1  3  4  5  1 24]


In [4]:
#What is the length of a np array?
l_np.size

6

In [5]:
#you can define an array of N zeros, or ones. Here N=15
zero_list = np.zeros(15)
print(zero_list)

one_list = np.ones(15)
print(one_list)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
#you can also create a range vector
a_r = np.arange(1,23)
a_r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [7]:
#you can also specify the step size, e.g. 0.25
a_r = np.arange(1,23,0.25)
a_r

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,
        3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,
        5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,
        7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
       10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75, 12.  ,
       12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  , 14.25,
       14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25, 16.5 ,
       16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 , 18.75,
       19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75, 21.  ,
       21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75])

In [10]:
#you can define the same "a_r" array giving the samber of elements as input
a_r = np.linspace(1, 22.75, 88)
a_r

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,
        3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,
        5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,
        7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
       10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75, 12.  ,
       12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  , 14.25,
       14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25, 16.5 ,
       16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 , 18.75,
       19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75, 21.  ,
       21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75])

In [14]:
#it is possible to separate the numers of an array logarithmically
a_rlog = np.logspace(1, 23, 4)
a_rlog

array([1.00000000e+01, 2.15443469e+08, 4.64158883e+15, 1.00000000e+23])

<h2>Manipulating arrays</h2>

In [15]:
#you can access the first, or last element of an array
print(a_r[0])
print(a_r[-1])

1.0
22.75


In [16]:
#or do a slicing, i.e. selecting a range
a_r[3:9]

array([1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ])

In [17]:
#or insert with np.insert(array,index,value)
np.insert(a_r,2,0.1)

array([ 1.  ,  1.25,  0.1 ,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,
        3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75])

In [18]:
#of course, you can convert the type of the elements
a_r.astype("int")

array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13,
       13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17,
       18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22,
       22, 22, 22])

<h2>Matrices</h2>

In [19]:
#Creating a matrix is also easy to do
a_mat = np.array([[ 2,  7, 12,],[17, 22, 27]])
print(a_mat)

[[ 2  7 12]
 [17 22 27]]


In [20]:
#and you can check the shape of the matrix with shape
a_mat.shape

(2, 3)

In [21]:
#you can even reshape it, e.g. to 1x6
a_mat.reshape(1,6)

array([[ 2,  7, 12, 17, 22, 27]])

In [22]:
a_mat.shape

(2, 3)

In [23]:
#let's multiply two matrices. The first is a 4x4 Identity.
m_id = np.eye(4)
m_id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
#then we can take a 16-vector and reshape
b_mat = np.arange(0,16)
b_mat = b_mat.reshape(4,4)
b_mat.shape

(4, 4)

In [25]:
#then multiply them
np.dot(m_id,b_mat)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [26]:
#given a matrix, you can sum its elements
np.sum(b_mat)

120

In [27]:
#or sum along the rows
np.sum(b_mat,axis=1)

array([ 6, 22, 38, 54])

In [28]:
#or the colums
np.sum(b_mat,axis=0)

array([24, 28, 32, 36])

In [29]:
#last thing, given a numpy array,you can compute various quantities, like the mean and the std
np.mean(a_r)

11.875

In [30]:
np.std(a_r)

6.350442897940269